image: docker


services:
 - docker:dind

before_script:
 - docker login https://registry.gitlab.com/ -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

stages:
 - build
 - test

build:
 stage: build
 script:
  - sed "s/latest_version/$CI_COMMIT_SHORT_SHA/" flatata-deployment.yaml
  - git add .
  - git push
  - docker pull $CI_REGISTRY_IMAGE:latest || true
  - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest --cache-from $CI_REGISTRY_IMAGE:latest
  - docker run $CI_REGISTRY_IMAGE:latest sed "s/latest_version/$CI_COMMIT_SHORT_SHA/" flatata-deployment.yaml
  - docker run $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA sed "s/latest_version/$CI_COMMIT_SHORT_SHA/" flatata-deployment.yaml
  - docker push $CI_REGISTRY_IMAGE:latest
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

test:
 stage: test
 script:
  - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  - docker run $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA yarn test

