image: docker


services:
 - docker:dind

before_script:
 - docker login https://registry.gitlab.com/ -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
 - VERS=$(cat version)

stages:
 - build
 - test

build:
 stage: build
 script:
  - docker pull $CI_REGISTRY_IMAGE:latest || true
  - docker build . -t $CI_REGISTRY_IMAGE:$VERS -t $CI_REGISTRY_IMAGE:latest --cache-from $CI_REGISTRY_IMAGE:latest
  - docker run $CI_REGISTRY_IMAGE:latest sed "s/latest_version/$VERS/" flatata-deployment.yaml
  - docker run $CI_REGISTRY_IMAGE:$VERS sed "s/latest_version/$VERS/" flatata-deployment.yaml
  - docker push $CI_REGISTRY_IMAGE:latest
  - docker push $CI_REGISTRY_IMAGE:$VERS

test:
 stage: test
 script:
  - docker pull $CI_REGISTRY_IMAGE:$VERS
  - docker run $CI_REGISTRY_IMAGE:$VERS yarn test

