image: docker


services:
 - docker:dind

before_script:
 - docker login https://registry.gitlab.com/ -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
 script:
  - docker pull registry.gitlab.com/mistrikoff/flatata:latest || true
  - docker build . -t registry.gitlab.com/mistrikoff/flatata:$CI_COMMIT_SHORT_SHA -t registry.gitlab.com/mistrikoff/flatata:latest --cache-from registry.gitlab.com/mistrikoff/flatata:latest
  - docker push registry.gitlab.com/mistrikoff/flatata:latest
  - docker push registry.gitlab.com/mistrikoff/flatata:$CI_COMMIT_SHORT_SHA
