image: docker


services:
 - docker:dind

before_script:
 - export 
 - docker login https://registry.gitlab.com/ -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
 script:
  - docker build . -t registry.gitlab.com/mistrikoff/flatata:latest
  - docker push registry.gitlab.com/mistrikoff/flatata:latest
